window.Pages = window.Pages || {};
Pages.model = {
  async render(el) {
    const report = await API.modelEvaluation();
    const bands = report?.risk_bands || {};
    el.innerHTML = `<div class="card"><div class="card-title-row"><h3>Allocation-pattern review model</h3></div><p style="font-size:12.5px;color:var(--ink-700);line-height:1.7;">The model is an Isolation Forest, an unsupervised method that identifies records whose allocation amounts are unusual relative to the imported set. It is not trained on fraud labels and its score is not a misconduct finding.</p>${report ? `<div class="grid grid-4 section-gap">${UI.kpiCard("Records scored", Fmt.num(report.total_records), { text: "Imported allocation rows" })}${UI.kpiCard("Low", Fmt.num(bands.Low || 0), { text: "Typical allocation pattern" })}${UI.kpiCard("Medium", Fmt.num(bands.Medium || 0), { text: "Worth a source check" })}${UI.kpiCard("High / Critical", Fmt.num((bands.High || 0) + (bands.Critical || 0)), { text: "Prioritised review prompts" })}</div>` : UI.empty("No training summary is available. Run the import and training commands.")}</div><div class="card section-gap"><div class="card-title-row"><h3>Inputs used now</h3></div><div class="check-list"><div><b>1</b><span><strong>Allocated amount</strong><small>Directly imported and compared across the bundled records.</small></span></div><div><b>2</b><span><strong>State and constituency context</strong><small>Used to display and filter records; not invented or inferred.</small></span></div></div></div><div class="card section-gap"><div class="card-title-row"><h3>Not assessed from this CSV</h3></div><p style="font-size:12.5px;color:var(--ink-700);line-height:1.7;">No project timelines, cost overruns, payment patterns, utilisation certificates, vendors, physical progress, locations, or compliance status can be calculated because those fields are not included in the supplied file. Add authorised work-level data before enabling those capabilities.</p></div>`;
  },
};
window.Pages = Pages;
