window.Pages = window.Pages || {};

Pages.quality = {
  async render(el, filters) {
    const data = await API.allocationAnalytics(filters);
    const c = data.coverage || {}, d = data.distribution || {};
    el.innerHTML = `<div class="info-banner"><strong>Source boundary.</strong> This application uses the supplied allocation CSV directly. It deliberately does not create payments, projects, dates, vendors, geo-coordinates, or compliance events that are absent from that source.</div><div class="grid grid-4 section-gap">${UI.kpiCard("Allocation records", Fmt.num(c.records || 0), { text: "Rows available in this scope" })}${UI.kpiCard("States", Fmt.num(c.states || 0), { text: "Distinct states represented" })}${UI.kpiCard("Constituencies", Fmt.num(c.constituencies || 0), { text: "Stored from source constituency field" })}${UI.kpiCard("MP records", Fmt.num(c.members || 0), { text: "Distinct MP / constituency entries" })}</div><div class="grid grid-2 section-gap">${UI.cardWrap("Allocation amount distribution", `<div class="kv-grid"><div><div class="kv-label">Minimum</div><div class="kv-value">${Fmt.lakh(d.min_lakh)}</div></div><div><div class="kv-label">25th percentile</div><div class="kv-value">${Fmt.lakh(d.p25_lakh)}</div></div><div><div class="kv-label">Median</div><div class="kv-value">${Fmt.lakh(d.median_lakh)}</div></div><div><div class="kv-label">75th percentile</div><div class="kv-value">${Fmt.lakh(d.p75_lakh)}</div></div><div><div class="kv-label">Maximum</div><div class="kv-value">${Fmt.lakh(d.max_lakh)}</div></div><div><div class="kv-label">Mean</div><div class="kv-value">${Fmt.lakh(d.mean_lakh)}</div></div></div>`)}${UI.cardWrap("Most common recorded amounts", data.common_amounts?.length ? `<div class="table-wrap"><table><thead><tr><th>Allocation amount</th><th>Records</th></tr></thead><tbody>${data.common_amounts.map(x => `<tr><td class="cell-amount">${Fmt.lakh(x.amount_lakh)}</td><td>${Fmt.num(x.count)}</td></tr>`).join("")}</tbody></table></div>` : UI.empty("No amounts available."))}</div><div class="card section-gap"><div class="card-title-row"><h3>Unavailable without additional authorised data</h3></div><div class="check-list"><div><b>1</b><span><strong>Execution and cost monitoring</strong><small>Requires work sanctions, estimates, payments and completion dates.</small></span></div><div><b>2</b><span><strong>Compliance monitoring</strong><small>Requires utilisation certificates, progress reports and formal workflow states.</small></span></div><div><b>3</b><span><strong>Vendor and map analysis</strong><small>Requires vendor, payment and verified geolocation records.</small></span></div></div></div>`;
  },
};
window.Pages = Pages;
